spring:
  datasource:
    url: jdbc:mysql://81.70.46.191:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: I7dYazi$wSyCNgML
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 81.70.46.191 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 5069 # Redis服务器连接端口
    password:  Qwer!!1234 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

logging:
  file:
    path: ./logs
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: localhost
common:
  getCodeUrl: "http://127.0.0.1:8090/common/mobile/getCode"
  checkCodeUrl: "http://127.0.0.1:8090/common/mobile/checkCode"
  updateMch: "http://127.0.0.1:8090/common/wx-pay-config/add"
sms:
  id: "AKID0oKfouBUvBTvBDbVLxLblxySo2N0AXR4"
  key: "XN3VSAfw2vb3IRM2uBCzAJDraDf5GxTm"
wx:
  pre_auth_code_url: https://api.weixin.qq.com/cgi-bin/component/api_create_preauthcode?component_access_token=COMPONENT_ACCESS_TOKEN
  api_component_token_url: https://api.weixin.qq.com/cgi-bin/component/api_component_token
  component_appid: wx4236aecd85ecef8e
  component_appsecret: 162db3c7f01ca324f5c0e82cc65fe1d2
  component_encodingAesKey: Qwer1234Qwer1234Qwer1234Qwer1234Qwer1234Qwe
  component_token: Qwer#@!1234
